version: '2'
services:
    agamotto-app:
        image: agamotto
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://agamotto-mysql:3306/agamotto?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=agamotto-elasticsearch:9300
        ports:
            - 8082:8082
    agamotto-mysql:
        extends:
            file: mysql.yml
            service: agamotto-mysql
    agamotto-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: agamotto-elasticsearch
