version: '2'
services:
    agamotto-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/agamotto/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=agamotto
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
